package ese4.controller;


import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import ese4.model.Package;
import ese4.model.PackageRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/package") // This means URL's start with /demo (after Application path)
public class PackageController {
	@Autowired // This means to get the bean called packageRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private PackageRepository packageRepository;

	
    @GetMapping("/all")
    public @ResponseBody Iterable<Package> allPackages() {        
    	return packageRepository.findAll();
    }	
	
    @GetMapping("/addPackageForm")
    public String addPackage(Model model) {
        model.addAttribute("package", new Package());
        return "addPackageForm";
    }

    @PostMapping("/addPackageForm")
    public String formSubmit(@ModelAttribute Package pack) {
    	packageRepository.save(pack);
        return "whatNext";
    }
    
    @ModelAttribute("packages")
    public Iterable<Package> allPackagesAsList() {
    	return this.packageRepository.findAll();
    }
    
    @GetMapping("/test")
    public String viewAllPackages(final Package pack) {
    	List<Package> testpacks;
  
    	System.out.println(packageRepository.count());
    	testpacks = packageRepository.findFirst2ByIsDeliveredFalse();	//we can later use this for extracting packages from repository
    	System.out.println("size is: " + testpacks.size());
    	if(testpacks.size()>1)
    	{
    		System.out.println(testpacks.get(0).getContent() + " and " + testpacks.get(1).getContent());
    		System.out.println(testpacks.get(0).getIsDelivered());
    		testpacks.get(0).setToDelivered();
    		packageRepository.save(testpacks.get(0));
    		System.out.println(testpacks.get(0).getIsDelivered());
    		//packageRepository.delete(testpacks);
    	}
    	
    	packageRepository.deleteByIsDelivered(true);
    	
    	return "testRead";
    }
}