package ese4.controller;


import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import ese4.model.Package;
import ese4.repository.PackageRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/package") // This means URL's start with /demo (after Application path)
public class PackageController {
	@Autowired // This means to get the bean called packageRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private PackageRepository packageRepository;

	
    @GetMapping()
    public String get() {
    	return "homeScreen";
    }	
    
    @GetMapping("/addPackageForm")
    public String addPackage(Model model) {
        model.addAttribute("package", new Package());
        return "package/addPackageForm";
    }

    @PostMapping("/addPackageForm")
    public String formSubmit(@ModelAttribute Package pack) {
    	packageRepository.save(pack);
        return "homescreen";
    }
    
    @ModelAttribute("packages")
    public Iterable<Package> allPackagesAsList() {
    	return this.packageRepository.findAll();
    }
    
    @GetMapping("/listAll")
    public String viewAllPackages() {
    	return "package/listAllPackages";
    }  
}